# Generated by Django 4.0.3 on 2022-04-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_stickersdima_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickersdima',
            options={'ordering': ['stickers_main'], 'verbose_name': 'Склад Діми', 'verbose_name_plural': 'Склад Діми'},
        ),
        migrations.AlterModelOptions(
            name='stickersmain',
            options={'ordering': ['pk'], 'verbose_name': 'Інфу про стікери', 'verbose_name_plural': 'Інфа про стікери'},
        ),
        migrations.AlterModelOptions(
            name='stickersvlad',
            options={'ordering': ['stickers_main'], 'verbose_name': 'Склад Влада', 'verbose_name_plural': 'Склад Влада'},
        ),
        migrations.AlterField(
            model_name='stickersdima',
            name='stickers_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_dima', to='storage.stickersmain', verbose_name='ID пака'),
        ),
        migrations.AlterField(
            model_name='stickersmain',
            name='photo',
            field=models.ImageField(height_field=350, upload_to='photos/', verbose_name='Фото', width_field=350),
        ),
        migrations.AlterField(
            model_name='stickersvlad',
            name='stickers_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_vlad', to='storage.stickersmain', verbose_name='ID пака'),
        ),
    ]
