# Generated by Django 4.0.3 on 2022-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_stickersdima_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickersmain',
            name='photo',
            field=models.ImageField(height_field='350', upload_to='photos/', verbose_name='Фото', width_field='350'),
        ),
    ]
