# Generated by Django 4.0.3 on 2022-04-04 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_stickersmain_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickersStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dima', models.IntegerField(default=0, verbose_name='Кількість у Діми')),
                ('quantity_vlad', models.IntegerField(default=0, verbose_name='Кількість у Влада')),
                ('stickers_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_dima', to='storage.stickersmain', verbose_name='ID пака')),
            ],
            options={
                'verbose_name': 'Склад Діми',
                'verbose_name_plural': 'Склад Діми',
                'ordering': ['stickers_main'],
            },
        ),
        migrations.RemoveField(
            model_name='stickersvlad',
            name='stickers_main',
        ),
        migrations.DeleteModel(
            name='StickersDima',
        ),
        migrations.DeleteModel(
            name='StickersVlad',
        ),
    ]
