# Generated by Django 4.0.3 on 2022-04-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_stickersstorage_remove_stickersvlad_stickers_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickersstorage',
            options={'ordering': ['stickers_main'], 'verbose_name': 'Склад стікерів', 'verbose_name_plural': 'Склад стікерів'},
        ),
        migrations.AlterField(
            model_name='stickersstorage',
            name='stickers_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_stickers', to='storage.stickersmain', verbose_name='ID пака'),
        ),
    ]
