# Generated by Django 4.0.3 on 2022-04-07 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='StickersMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Загальна кількість')),
                ('quantity_in_pack', models.IntegerField(default=50, verbose_name='В паці')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Інфу про стікери',
                'verbose_name_plural': 'Інфа про стікери',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StickersStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dima', models.IntegerField(default=0, verbose_name='Кількість у Діми')),
                ('quantity_vlad', models.IntegerField(default=0, verbose_name='Кількість у Влада')),
                ('stickers_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_stickers', to='storage.stickersmain', verbose_name='ID пака')),
            ],
            options={
                'verbose_name': 'Склад стікерів',
                'verbose_name_plural': 'Склад стікерів',
                'ordering': ['stickers_main'],
            },
        ),
    ]
