# Generated by Django 4.0.3 on 2022-03-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_category_options_alter_stickersmain_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickersmain',
            options={'verbose_name': 'Інфа про стікери', 'verbose_name_plural': 'Інфу про стікери'},
        ),
    ]
