# Generated by Django 4.0.3 on 2022-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_stickersdima_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickersdima',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кількість у Діми'),
        ),
        migrations.AlterField(
            model_name='stickersvlad',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кількість у Влада'),
        ),
    ]
