# Generated by Django 4.0.3 on 2022-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_stickersmain_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickersmain',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
