# Generated by Django 4.0.3 on 2022-04-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'processing'), (2, 'success'), (3, 'error')], default=1, verbose_name='Статус замовлення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('price', models.IntegerField(verbose_name='Сума')),
                ('ttn', models.CharField(blank=True, max_length=255, verbose_name='ТТН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запаковує')),
            ],
            options={
                'verbose_name': 'Інфу про стікери',
                'verbose_name_plural': 'Інфа про стікери',
                'ordering': ['pk'],
            },
        ),
    ]
