# Generated by Django 4.0.3 on 2022-04-07 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'processing'), (2, 'success'), (3, 'error')], default=1, verbose_name='Статус замовлення')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('price', models.IntegerField(verbose_name='Сума')),
                ('ttn', models.CharField(blank=True, max_length=255, verbose_name='ТТН')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запаковує')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.BooleanField(default=True, verbose_name='В корзині?')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.category', verbose_name='Категорія')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.stickersmain', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запаковує')),
            ],
            options={
                'verbose_name': 'Товар в замовлення',
                'verbose_name_plural': 'Товари в замовленні',
                'ordering': ['pk'],
            },
        ),
    ]
