# Generated by Django 4.0.3 on 2022-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_alter_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='bag',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Кількість'),
        ),
    ]
