# Generated by Django 4.0.3 on 2022-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обробка'), (2, 'Виконано'), (3, 'Помилка')], default=1, verbose_name='Статус замовлення'),
        ),
    ]
