# Generated by Django 4.0.3 on 2022-04-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_alter_order_user_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['pk'], 'verbose_name': 'Товар в замовлення', 'verbose_name_plural': 'Товари в замовленні'},
        ),
    ]
