# Generated by Django 4.0.3 on 2022-04-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
        ('order_management', '0004_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bag.bag', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order_management.order', verbose_name='Замовлення'),
        ),
    ]
