# Generated by Django 4.0.3 on 2022-04-05 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='bag',
            field=models.BooleanField(default=True, verbose_name='В корзині?'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_management.order', verbose_name='Замовлення'),
            preserve_default=False,
        ),
    ]
