# Generated by Django 4.0.3 on 2022-04-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_alter_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='bag',
        ),
    ]
