# Generated by Django 4.0.3 on 2022-04-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bag', '0002_account_alter_bag_price_alter_bag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='id',
        ),
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Запаковує'),
        ),
    ]
