# Generated by Django 4.0.3 on 2022-04-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0006_alter_bag_price_alter_bag_ttn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
