# Generated by Django 4.0.3 on 2022-04-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_remove_bag_id_alter_bag_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
