# Generated by Django 4.0.3 on 2022-04-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_stickersstorage_stickers_main'),
        ('bag', '0003_alter_bagproduct_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='storage.stickersmain', verbose_name='Товар'),
        ),
    ]
