# Generated by Django 4.0.3 on 2022-04-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_alter_bag_price_alter_bag_ttn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagproduct',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_products', to='bag.bag', verbose_name='Корзина'),
        ),
    ]
