# Generated by Django 4.0.3 on 2022-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='ttn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ТТН'),
        ),
    ]
